[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  # Configure secrets scanning - skip SUPABASE_URL as it's a public URL safe to expose
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL"
  SECRETS_SCAN_OMIT_PATHS = "EMAIL_SETUP.md,README.md,*.md,index-backup.html,.next/**/*,out/**/*,node_modules/**/*,.netlify/**/*"

# Next.js on Netlify plugin for server-side features
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Remove the catch-all redirect since Next.js will handle routing
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
