import type { Locale } from './locales'

const en = {
  home: 'Home', work: 'Work', about: 'About', contact: 'Contact', menu: 'Menu', close: 'Close menu', language: 'Language', skip: 'Skip to content',
  eyebrow: 'Builder · Gaming · Malaysia', hello: 'Hi, I’m Neo.', headline: 'I build apps, games & useful AI.',
  intro: 'I’m Ahmad Fadli, CEO of Todak Studios. I turn everyday problems and curious ideas into things people can use and play.',
  roles: 'CEO, Todak Studios Sdn Bhd · Researcher, PT Todak Nusantara Group (Bandung, Indonesia)',
  explore: 'Explore my work', moreAbout: 'More about me', portraitAlt: 'Neo Todak smiling in sunglasses at a temple in Bali.',
  recent: 'A few things I’ve been building.', allProjects: 'All projects', app: 'App', game: 'Game', testing: 'In testing', released: 'On the App Store · Google Play',
  foodTagline: 'Less deciding. More makan.', foodSummary: 'An app to help you decide what to eat and find it nearby.', exploreApp: 'Explore the app',
  rushTagline: 'A little chaos in a Malaysian pasar.', rushSummary: 'An offline police-and-robbers chase through a Malaysian market.', seeGame: 'See the game',
  foodAlt: 'The current ApaNakMakan swipe screen, showing nasi lemak, like and dislike controls, and saved dishes.', rushAlt: 'Promotional illustration of a police officer chasing a robber through a colourful Malaysian market.',
  peek: 'A peek into my AI world', citySummary: 'A living map of the AI agents that run my work.', openCity: 'Open NACA City', cityAlt: 'The public NACA City map, with isometric islands representing parts of Neo’s AI world.', cityCaption: 'A snapshot of the public map. Explore the city to look around.',
  aboutTitle: 'Curious by nature. A builder at heart.', aboutSummary: 'My work brings together games, everyday apps and AI experiments. This is where I share what I’m making and what I’m learning.',
  moreWork: 'More from my work', ai: 'AI experiments', studio: 'Games with Todak Studios', story: 'My story',
  contactTitle: 'Have something in mind?', talk: 'Let’s talk', footerLine: 'Build. Play. Keep learning.', back: 'Back to work',
  workTitle: 'Ideas turned into things.', workIntro: 'Apps to make everyday choices easier, games to get lost in, and experiments that help me work. A collection of what I’ve built and contributed to.',
  latest: 'Recent projects', lab: 'From the lab', earlier: 'Earlier experiments', earlierIntro: 'Past work and stepping stones. These projects are part of the journey; they are not offered here as current products.',
  studioIntro: 'Games from the Todak Studios team. My role is CEO of Todak Studios Sdn Bhd; the work belongs to the people who make it together.', visitStudio: 'Visit Todak Studios',
  what: 'What it does', why: 'Where it started', role: 'My role', today: 'Where it is today',
  foodWhat: 'Swipe through dishes, keep the ones you like, and discover places to eat nearby. ApaNakMakan begins with the question we ask every day: what shall we eat?',
  foodWhy: 'Choosing a meal should be the easy part. This project brings the food to the front, so you can start with what looks good to you.',
  foodRole: 'This is my personal app project. I shape the idea and product direction, and work through the experience as it is built and tested.',
  foodToday: 'ApaNakMakan is in testing. Visit the app website for its introduction and launch updates.',
  foodScreen: 'Current iPhone swipe screen', photoCredit: 'Food photo', originalPhoto: 'Original photo',
  rushWhat: 'Pick a side and chase through a stylised Malaysian pasar. Play as police or a robber, hide, vault counters and keep the chase going. You play solo with bots, fully offline.',
  rushWhy: 'A familiar Malaysian setting turns a simple chase into something playful: busy stalls, tight corners and a banana peel at the wrong moment.',
  rushRole: 'CEO, Todak Studios Sdn Bhd. police sentri : RUSH is published by Todak Studios and is credited to the Todak Studios team.',
  rushToday: 'Available on the App Store and Google Play. This is police sentri : RUSH, a separate title from Police Sentri 2 and TAG Police Sentri.',
  apple: 'View on the App Store', google: 'View on Google Play', promo: 'Promotional illustration by the project’s creative team; not a gameplay screenshot.',
  aiTitle: 'A little of what’s under the hood.', aiIntro: 'I explore how AI can remember context, organise work and help an idea become something real. Here are some of the pieces.',
  twinTitle: 'Meet the AI twin', twinText: 'An optional chat with an AI representation of me. It can make mistakes and is not a conversation with the real Neo. The existing chat opens in English.', twinAction: 'Open the AI twin',
  aboutIntro: 'I’m Ahmad Fadli, better known as Neo Todak. I work across games, everyday software and AI research.',
  aboutBody: 'I’m interested in the space between an idea and something you can actually use. Sometimes that becomes an app that helps you choose lunch. Sometimes it becomes a game, or a small tool that makes work easier.',
  aboutBody2: 'At Todak Studios, I lead as CEO and work with the studio team. My research role at PT Todak Nusantara Group connects my work with Bandung, Indonesia. This portfolio brings those interests together, with room for the experiments along the way.',
  aboutLink: 'See what I’m working on', contactIntro: 'An idea, a game, a useful problem to solve? Say hello. I’m happy to hear what you have in mind.', email: 'Email me', elsewhere: 'Find me elsewhere', studioContact: 'For studio projects', studioContactText: 'For game development and creative production, meet the team at Todak Studios.',
  meta: 'Ahmad Fadli — Neo Todak. Apps, games and useful AI. CEO of Todak Studios Sdn Bhd and researcher at PT Todak Nusantara Group.',
}
export type Copy = { [K in keyof typeof en]: string }

const ms: Copy = {
  home: 'Utama', work: 'Projek', about: 'Tentang saya', contact: 'Hubungi', menu: 'Menu', close: 'Tutup menu', language: 'Bahasa', skip: 'Terus ke kandungan',
  eyebrow: 'Pencipta · Permainan · Malaysia', hello: 'Hai, saya Neo.', headline: 'Saya membina aplikasi, permainan dan AI yang berguna.',
  intro: 'Saya Ahmad Fadli, CEO Todak Studios. Saya suka meneroka idea baharu dan menyelesaikan masalah harian melalui aplikasi, permainan dan teknologi.',
  roles: 'CEO, Todak Studios Sdn Bhd · Penyelidik, PT Todak Nusantara Group (Bandung, Indonesia)',
  explore: 'Lihat projek saya', moreAbout: 'Kenali saya', portraitAlt: 'Neo Todak tersenyum sambil memakai cermin mata hitam di sebuah pura di Bali.',
  recent: 'Antara projek yang saya usahakan.', allProjects: 'Semua projek', app: 'Aplikasi', game: 'Permainan', testing: 'Dalam ujian', released: 'Di App Store · Google Play',
  foodTagline: 'Kurang berfikir. Jom makan.', foodSummary: 'Aplikasi untuk membantu anda memilih makanan dan mencari tempat makan berdekatan.', exploreApp: 'Lihat aplikasi',
  rushTagline: 'Riuh-rendah di pasar Malaysia.', rushSummary: 'Permainan kejar-mengejar polis dan pencuri di pasar Malaysia, tanpa internet.', seeGame: 'Lihat permainan',
  foodAlt: 'Skrin leret terkini ApaNakMakan yang memaparkan nasi lemak, pilihan suka dan tidak suka, serta makanan yang disimpan.', rushAlt: 'Ilustrasi promosi seorang polis mengejar pencuri di pasar Malaysia yang berwarna-warni.',
  peek: 'Jenguk dunia AI saya', citySummary: 'Peta hidup ejen AI yang mengurus kerja saya.', openCity: 'Buka NACA City', cityAlt: 'Peta awam NACA City dengan pulau isometrik yang mewakili bahagian dunia AI Neo.', cityCaption: 'Gambaran peta awam. Buka bandar ini untuk menerokanya.',
  aboutTitle: 'Suka meneroka. Gemar mencipta.', aboutSummary: 'Kerja saya menggabungkan permainan, aplikasi harian dan eksperimen AI. Di sinilah saya berkongsi apa yang sedang saya bina dan pelajari.',
  moreWork: 'Lagi hasil kerja saya', ai: 'Eksperimen AI', studio: 'Permainan bersama Todak Studios', story: 'Kisah saya',
  contactTitle: 'Ada idea dalam fikiran?', talk: 'Jom berbual', footerLine: 'Cipta. Main. Terus belajar.', back: 'Kembali ke projek',
  workTitle: 'Daripada idea menjadi nyata.', workIntro: 'Aplikasi untuk memudahkan pilihan harian, permainan untuk dinikmati dan eksperimen yang membantu kerja saya. Inilah projek yang saya bina dan sumbangkan.',
  latest: 'Projek terkini', lab: 'Dari makmal', earlier: 'Eksperimen terdahulu', earlierIntro: 'Hasil kerja lama dan langkah dalam perjalanan saya. Projek ini dikongsi sebagai sejarah, bukan ditawarkan sebagai produk semasa.',
  studioIntro: 'Permainan hasil pasukan Todak Studios. Peranan saya ialah CEO Todak Studios Sdn Bhd; hasilnya milik semua yang menciptanya bersama.', visitStudio: 'Lawati Todak Studios',
  what: 'Fungsinya', why: 'Asal ideanya', role: 'Peranan saya', today: 'Status semasa',
  foodWhat: 'Leret untuk melihat hidangan, simpan yang anda suka dan cari tempat makan berdekatan. ApaNakMakan bermula dengan soalan yang kita tanya setiap hari: nak makan apa?',
  foodWhy: 'Memilih makanan sepatutnya mudah. Projek ini mengutamakan gambar hidangan supaya anda boleh bermula dengan apa yang menyelerakan.',
  foodRole: 'Ini projek aplikasi peribadi saya. Saya membentuk idea dan hala tuju produk serta meneliti pengalaman pengguna sepanjang pembangunan dan ujian.',
  foodToday: 'ApaNakMakan sedang diuji. Lawati laman aplikasinya untuk pengenalan dan berita pelancaran.',
  foodScreen: 'Skrin leret iPhone terkini', photoCredit: 'Foto makanan', originalPhoto: 'Foto asal',
  rushWhat: 'Pilih pihak dan kejar-mengejar di pasar Malaysia yang digayakan. Jadi polis atau pencuri, bersembunyi, lompat kaunter dan teruskan pengejaran. Main secara solo bersama bot, tanpa internet.',
  rushWhy: 'Suasana pasar Malaysia menjadikan permainan kejar-mengejar lebih menyeronokkan: gerai yang sibuk, lorong sempit dan kulit pisang pada saat yang tidak dijangka.',
  rushRole: 'CEO, Todak Studios Sdn Bhd. police sentri : RUSH diterbitkan oleh Todak Studios dan merupakan hasil pasukan Todak Studios.',
  rushToday: 'Tersedia di App Store dan Google Play. Ini police sentri : RUSH, judul yang berbeza daripada Police Sentri 2 dan TAG Police Sentri.',
  apple: 'Lihat di App Store', google: 'Lihat di Google Play', promo: 'Ilustrasi promosi oleh pasukan kreatif projek; bukan tangkap layar permainan.',
  aiTitle: 'Di sebalik hasil kerja saya.', aiIntro: 'Saya meneroka bagaimana AI boleh mengingati konteks, menyusun kerja dan membantu merealisasikan idea. Ini antara bahagiannya.',
  twinTitle: 'Kenali kembar AI saya', twinText: 'Sembang pilihan dengan versi AI yang mewakili saya. Ia boleh tersilap dan bukan perbualan dengan Neo sebenar. Sembang sedia ada dibuka dalam bahasa Inggeris.', twinAction: 'Buka kembar AI',
  aboutIntro: 'Saya Ahmad Fadli, lebih dikenali sebagai Neo Todak. Saya bekerja dalam bidang permainan, perisian harian dan penyelidikan AI.',
  aboutBody: 'Saya tertarik dengan proses mengubah idea menjadi sesuatu yang boleh digunakan. Kadangkala hasilnya aplikasi untuk memilih makan tengah hari. Kadangkala permainan atau alat kecil yang memudahkan kerja.',
  aboutBody2: 'Di Todak Studios, saya memimpin sebagai CEO dan bekerja bersama pasukan studio. Peranan penyelidikan saya di PT Todak Nusantara Group menghubungkan kerja saya dengan Bandung, Indonesia. Portfolio ini menghimpunkan minat tersebut, termasuk eksperimen sepanjang perjalanan.',
  aboutLink: 'Lihat apa yang saya usahakan', contactIntro: 'Ada idea, permainan atau masalah yang ingin diselesaikan? Tegurlah saya. Saya sudi mendengar apa yang ada dalam fikiran anda.', email: 'E-mel saya', elsewhere: 'Temui saya di sini', studioContact: 'Untuk projek studio', studioContactText: 'Untuk pembangunan permainan dan produksi kreatif, kenali pasukan Todak Studios.',
  meta: 'Ahmad Fadli — Neo Todak. Aplikasi, permainan dan AI yang berguna. CEO Todak Studios Sdn Bhd dan penyelidik di PT Todak Nusantara Group.',
}

const id: Copy = {
  home: 'Beranda', work: 'Karya', about: 'Tentang saya', contact: 'Kontak', menu: 'Menu', close: 'Tutup menu', language: 'Bahasa', skip: 'Langsung ke konten',
  eyebrow: 'Kreator · Game · Malaysia', hello: 'Hai, saya Neo.', headline: 'Saya membuat aplikasi, game, dan AI yang bermanfaat.',
  intro: 'Saya Ahmad Fadli, CEO Todak Studios. Saya senang mengeksplorasi ide baru dan memecahkan masalah sehari-hari melalui aplikasi, game, dan teknologi.',
  roles: 'CEO, Todak Studios Sdn Bhd · Peneliti, PT Todak Nusantara Group (Bandung, Indonesia)',
  explore: 'Lihat karya saya', moreAbout: 'Kenali saya', portraitAlt: 'Neo Todak tersenyum mengenakan kacamata hitam di sebuah pura di Bali.',
  recent: 'Beberapa hal yang sedang saya kerjakan.', allProjects: 'Semua karya', app: 'Aplikasi', game: 'Game', testing: 'Dalam pengujian', released: 'Di App Store · Google Play',
  foodTagline: 'Tak perlu bingung. Yuk, makan.', foodSummary: 'Aplikasi untuk membantu memilih makanan dan menemukan tempat makan terdekat.', exploreApp: 'Jelajahi aplikasinya',
  rushTagline: 'Sedikit kekacauan di pasar Malaysia.', rushSummary: 'Game kejar-kejaran polisi dan pencuri di pasar Malaysia, tanpa internet.', seeGame: 'Lihat gamenya',
  foodAlt: 'Layar geser terbaru ApaNakMakan yang menampilkan nasi lemak, tombol suka dan tidak suka, serta makanan tersimpan.', rushAlt: 'Ilustrasi promosi polisi mengejar pencuri di pasar Malaysia yang penuh warna.',
  peek: 'Mengintip dunia AI saya', citySummary: 'Peta hidup para agen AI yang menjalankan pekerjaan saya.', openCity: 'Buka NACA City', cityAlt: 'Peta publik NACA City dengan pulau-pulau isometrik yang mewakili bagian dunia AI Neo.', cityCaption: 'Cuplikan peta publik. Buka kotanya untuk menjelajah.',
  aboutTitle: 'Selalu ingin tahu. Senang berkarya.', aboutSummary: 'Karya saya mempertemukan game, aplikasi sehari-hari, dan eksperimen AI. Di sini saya berbagi apa yang sedang saya buat dan pelajari.',
  moreWork: 'Karya saya lainnya', ai: 'Eksperimen AI', studio: 'Game bersama Todak Studios', story: 'Cerita saya',
  contactTitle: 'Ada ide yang ingin dibahas?', talk: 'Mari ngobrol', footerLine: 'Berkarya. Bermain. Terus belajar.', back: 'Kembali ke karya',
  workTitle: 'Dari ide menjadi nyata.', workIntro: 'Aplikasi untuk memudahkan pilihan sehari-hari, game untuk dinikmati, dan eksperimen yang membantu pekerjaan saya. Kumpulan proyek yang saya buat dan ikuti.',
  latest: 'Proyek terbaru', lab: 'Dari laboratorium', earlier: 'Eksperimen terdahulu', earlierIntro: 'Karya lama dan langkah-langkah dalam perjalanan saya. Proyek ini dibagikan sebagai riwayat, bukan ditawarkan sebagai produk saat ini.',
  studioIntro: 'Game karya tim Todak Studios. Peran saya adalah CEO Todak Studios Sdn Bhd; hasilnya merupakan karya bersama orang-orang di baliknya.', visitStudio: 'Kunjungi Todak Studios',
  what: 'Apa fungsinya', why: 'Awal idenya', role: 'Peran saya', today: 'Status saat ini',
  foodWhat: 'Geser untuk melihat hidangan, simpan yang Anda suka, dan temukan tempat makan terdekat. ApaNakMakan berawal dari pertanyaan yang kita ajukan setiap hari: mau makan apa?',
  foodWhy: 'Memilih makanan seharusnya mudah. Proyek ini mengutamakan tampilan hidangan agar Anda bisa mulai dari makanan yang menggugah selera.',
  foodRole: 'Ini proyek aplikasi pribadi saya. Saya membentuk ide dan arah produk, serta mengevaluasi pengalaman pengguna selama pengembangan dan pengujian.',
  foodToday: 'ApaNakMakan sedang dalam pengujian. Kunjungi situs aplikasinya untuk pengenalan dan kabar peluncuran.',
  foodScreen: 'Layar geser iPhone terbaru', photoCredit: 'Foto makanan', originalPhoto: 'Foto asli',
  rushWhat: 'Pilih pihak dan berkejaran di pasar Malaysia bergaya kartun. Jadilah polisi atau pencuri, bersembunyi, lompati konter, dan teruskan pengejaran. Bermain sendiri bersama bot, sepenuhnya tanpa internet.',
  rushWhy: 'Suasana pasar Malaysia membuat kejar-kejaran sederhana menjadi seru: kios ramai, lorong sempit, dan kulit pisang di saat yang tidak tepat.',
  rushRole: 'CEO, Todak Studios Sdn Bhd. police sentri : RUSH diterbitkan oleh Todak Studios dan merupakan karya tim Todak Studios.',
  rushToday: 'Tersedia di App Store dan Google Play. Ini police sentri : RUSH, judul yang berbeda dari Police Sentri 2 dan TAG Police Sentri.',
  apple: 'Lihat di App Store', google: 'Lihat di Google Play', promo: 'Ilustrasi promosi oleh tim kreatif proyek; bukan tangkapan layar permainan.',
  aiTitle: 'Sedikit cerita di balik layar.', aiIntro: 'Saya mengeksplorasi bagaimana AI dapat mengingat konteks, mengatur pekerjaan, dan membantu mewujudkan ide. Inilah beberapa bagiannya.',
  twinTitle: 'Kenali kembaran AI saya', twinText: 'Obrolan opsional dengan versi AI yang mewakili saya. AI bisa keliru dan ini bukan percakapan dengan Neo yang sebenarnya. Obrolan yang sudah ada dibuka dalam bahasa Inggris.', twinAction: 'Buka kembaran AI',
  aboutIntro: 'Saya Ahmad Fadli, lebih dikenal sebagai Neo Todak. Saya berkarya di bidang game, perangkat lunak sehari-hari, dan riset AI.',
  aboutBody: 'Saya tertarik pada proses mengubah ide menjadi sesuatu yang bisa digunakan. Kadang hasilnya aplikasi untuk memilih makan siang. Kadang sebuah game atau alat kecil yang memudahkan pekerjaan.',
  aboutBody2: 'Di Todak Studios, saya memimpin sebagai CEO dan bekerja bersama tim studio. Peran riset saya di PT Todak Nusantara Group menghubungkan pekerjaan saya dengan Bandung, Indonesia. Portfolio ini mempertemukan minat tersebut, beserta eksperimen sepanjang perjalanannya.',
  aboutLink: 'Lihat yang sedang saya kerjakan', contactIntro: 'Punya ide, game, atau masalah yang ingin diselesaikan? Sapa saya. Saya senang mendengar apa yang Anda pikirkan.', email: 'Kirim email', elsewhere: 'Temukan saya di sini', studioContact: 'Untuk proyek studio', studioContactText: 'Untuk pengembangan game dan produksi kreatif, kenali tim Todak Studios.',
  meta: 'Ahmad Fadli — Neo Todak. Aplikasi, game, dan AI yang bermanfaat. CEO Todak Studios Sdn Bhd dan peneliti di PT Todak Nusantara Group.',
}

const zh: Copy = {
  home: '首页', work: '作品', about: '关于我', contact: '联系', menu: '菜单', close: '关闭菜单', language: '语言', skip: '跳至正文',
  eyebrow: '创造 · 游戏 · 马来西亚', hello: '你好，我是 Neo。', headline: '我开发应用、游戏和实用的 AI 工具。',
  intro: '我是 Ahmad Fadli，Todak Studios 的首席执行官。我喜欢探索新想法，通过应用、游戏和技术解决日常生活中的问题。',
  roles: 'Todak Studios Sdn Bhd 首席执行官 · PT Todak Nusantara Group 研究员（印度尼西亚万隆）',
  explore: '看看我的作品', moreAbout: '了解我', portraitAlt: 'Neo Todak 戴着太阳镜，在巴厘岛的一座寺庙前微笑。',
  recent: '最近，我在做这些。', allProjects: '全部作品', app: '应用', game: '游戏', testing: '测试中', released: '已上架 App Store · Google Play',
  foodTagline: '少点纠结，好好吃饭。', foodSummary: '帮你决定吃什么，再找到附近的好去处。', exploreApp: '了解这款应用',
  rushTagline: '马来西亚市集里的追逐趣事。', rushSummary: '在马来西亚市集里追捕或逃脱，无需联网。', seeGame: '了解这款游戏',
  foodAlt: 'ApaNakMakan 最新滑动界面，展示椰浆饭、喜欢与不喜欢按钮，以及收藏的菜品。', rushAlt: '游戏宣传插画：警察在色彩鲜艳的马来西亚市集中追逐小偷。',
  peek: '来看看我的 AI 世界', citySummary: '一张生动的地图，展示协助我工作的 AI 智能体。', openCity: '打开 NACA City', cityAlt: 'NACA City 公开地图，用等距视角的岛屿展示 Neo 的 AI 世界。', cityCaption: '公开地图的截图。打开这座城市，随意探索。',
  aboutTitle: '好奇是起点，创造是日常。', aboutSummary: '我的工作融合了游戏、日常应用和 AI 实验。我在这里分享正在做的项目，以及一路学到的东西。',
  moreWork: '更多作品', ai: 'AI 实验', studio: '与 Todak Studios 一起做的游戏', story: '我的故事',
  contactTitle: '有什么想法想聊聊？', talk: '聊一聊', footerLine: '创造，玩乐，不断学习。', back: '返回作品',
  workTitle: '让想法成为现实。', workIntro: '让日常选择更轻松的应用、让人投入其中的游戏，还有协助我工作的实验。这里收录了我创作与参与的项目。',
  latest: '近期项目', lab: '实验室里的探索', earlier: '以往的实验', earlierIntro: '过去的作品，也是一路走来的足迹。这些项目作为创作记录展示，并不代表目前仍对外提供服务。',
  studioIntro: '这些游戏由 Todak Studios 团队创作。我担任 Todak Studios Sdn Bhd 首席执行官，每部作品都凝聚了团队成员的心血。', visitStudio: '访问 Todak Studios',
  what: '它能做什么', why: '想法的起点', role: '我的角色', today: '目前进展',
  foodWhat: '滑动浏览菜品，收藏喜欢的食物，再寻找附近的餐厅。ApaNakMakan 从一个每天都会遇到的问题出发：今天吃什么？',
  foodWhy: '选一顿饭本该很轻松。这个项目把食物放在最显眼的位置，让你从眼前喜欢的菜品开始选择。',
  foodRole: '这是我的个人应用项目。我负责构思和产品方向，并在开发与测试过程中不断体验和打磨它。',
  foodToday: 'ApaNakMakan 目前正在测试中。欢迎访问应用网站，了解产品介绍和上线消息。',
  foodScreen: '最新 iPhone 滑动界面', photoCredit: '食物照片', originalPhoto: '原始照片',
  rushWhat: '选择阵营，在风格鲜明的马来西亚市集里追逐。扮演警察或小偷，躲藏、翻越摊位，继续追捕或逃脱。单人游玩，其余角色由电脑控制，全程无需联网。',
  rushWhy: '熟悉的马来西亚市集让简单的追逐充满乐趣：热闹的摊位、狭窄的转角，以及突然出现在脚下的香蕉皮。',
  rushRole: '我担任 Todak Studios Sdn Bhd 首席执行官。police sentri : RUSH 由 Todak Studios 发行，作品归功于 Todak Studios 团队。',
  rushToday: '现已上架 App Store 和 Google Play。police sentri : RUSH 是独立的游戏作品，与 Police Sentri 2 和 TAG Police Sentri 不同。',
  apple: '前往 App Store', google: '前往 Google Play', promo: '项目创作团队制作的宣传插画，非游戏实机截图。',
  aiTitle: '看看作品背后的探索。', aiIntro: '我探索 AI 如何记住上下文、安排工作，并帮助想法落地。这些是其中的一部分。',
  twinTitle: '认识我的 AI 分身', twinText: '你可以选择与代表我的 AI 分身聊天。它可能会出错，这并非与 Neo 本人交谈。现有聊天界面使用英语。', twinAction: '打开 AI 分身',
  aboutIntro: '我是 Ahmad Fadli，大家更熟悉的名字是 Neo Todak。我从事游戏、日常软件和 AI 研究。',
  aboutBody: '我对把想法变成可用事物的过程充满兴趣。有时，成果是一款帮你决定午餐吃什么的应用；有时是一款游戏，或一个让工作更轻松的小工具。',
  aboutBody2: '在 Todak Studios，我担任首席执行官，与工作室团队一起工作。我在 PT Todak Nusantara Group 的研究角色，也把我的工作与印度尼西亚万隆联系起来。这份作品集汇集了这些兴趣，以及沿途的尝试。',
  aboutLink: '看看我正在做什么', contactIntro: '有个想法、一款游戏，或一个值得解决的问题？欢迎打个招呼。我很乐意听听你的想法。', email: '给我发邮件', elsewhere: '也可以在这里找到我', studioContact: '工作室项目', studioContactText: '如需游戏开发和创意制作，欢迎认识 Todak Studios 团队。',
  meta: 'Ahmad Fadli — Neo Todak。应用、游戏与实用的 AI。Todak Studios Sdn Bhd 首席执行官，PT Todak Nusantara Group 研究员。',
}

export const copy: Record<Locale, Copy> = { en, ms, id, zh }
